language: python
matrix:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install -r requirements.txt
script:
  python3 -m unittest discover -v -s './tests' -p 'test_*.py' || python -m unittest discover -v -s './tests' -p 'test_*.py'